import { NgModule } from '@angular/core';
import {
  MatMenuModule,
  MatDialogModule,
  MatTabsModule,
  MatBadgeModule,
  MatExpansionModule,
  MatButtonModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatFormFieldModule,
  MatChipsModule,
  MatSlideToggleModule,
  MatTooltipModule,
  MatCheckboxModule,
  MatInputModule,
  MatButtonToggleModule,
  MatListModule,
  MatDividerModule,
  MatSelectModule,
  MatPaginatorModule,
  MatRadioModule,
  MatGridListModule,
  MatDatepickerModule,
  MatProgressBarModule,
  MatSidenavModule,
  MatSnackBarModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatMenuModule,
    MatDialogModule,
    MatTabsModule,
    MatBadgeModule,
    MatExpansionModule,
    MatSnackBarModule
  ],
  exports: [
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatChipsModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatInputModule,
    MatButtonToggleModule,
    MatListModule,
    MatDividerModule,
    MatSelectModule,
    MatPaginatorModule,
    MatRadioModule,
    MatGridListModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatTabsModule,
    MatBadgeModule,
    MatExpansionModule,
    MatSidenavModule,
    MatSnackBarModule,
  ]
})
export class MaterialModule {}
